version: "3.9"

services:
  s_prod:
    build:
      context: .
      dockerfile: Dockerfile_p
    networks:
      - myredis

  s_cons:
    build:
      context: .
      dockerfile: Dockerfile_c
    networks:
      - myredis

networks:
  myredis:
    driver: bridge
